// `parser/pkg/name_name_parser_bg.wasm` を `frontend/src/wasm/wasm-bytes.generated.ts`
// に base64 文字列として書き出す。
//
// 経緯:
//   - `?fs/` 経由 / public 経由 / `?url` のいずれも、corp proxy 配下では
//     JS 経由の fetch が intercept され HTML に差し替えられる事象があった
//     (Accept / Sec-Fetch-Dest ヘッダで proxy が分岐) 。
//   - 確実に届けるため、WASM 本体を JS バンドルに base64 で同梱する方針に切替。
//   - サイズ: 189 KiB → base64 で約 250 KiB。一回のロードのみ。
//
// build / dev の前に必ず動く (predev / prebuild)。
import { readFile, writeFile, stat } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.resolve(__dirname, "../../parser/pkg/name_name_parser_bg.wasm");
const DST = path.resolve(__dirname, "../src/wasm/wasm-bytes.generated.ts");

async function fileExists(p) {
  try {
    await stat(p);
    return true;
  } catch {
    return false;
  }
}

if (!(await fileExists(SRC))) {
  console.error(`[sync-wasm] missing source: ${SRC}`);
  process.exit(1);
}
const buf = await readFile(SRC);
const b64 = buf.toString("base64");
const tsContent = `// AUTO-GENERATED by frontend/scripts/sync-wasm.mjs — do not edit by hand.
// Source: parser/pkg/name_name_parser_bg.wasm (${buf.byteLength} bytes)
//
// 詳細は frontend/scripts/sync-wasm.mjs のコメント参照。
// JS 経由 fetch を proxy が握る環境でも届けるため、WASM を base64 で同梱する。
export const WASM_BASE64 = ${JSON.stringify(b64)};
`;
await writeFile(DST, tsContent, "utf-8");
console.log(`[sync-wasm] ${path.relative(process.cwd(), DST)} (${buf.byteLength} bytes)`);
